server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_logger
    username: root
    password: tjahfoq12
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      location: C:\Users\junsang\Desktop\test_file_dir
      max-request-size: 1000MB
      max-file-size: 1000MB

  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration